name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set version
      run: echo 'VERSION=$(date +%s)' >> $GITHUB_ENV

    - uses: docker/login-action@v3.1.0
      with:
        username: jamesread
        password: ${{ secrets.CONTAINER_TOKEN }}
        registry: ghcr.io

    - name: Build the Docker image
      run: docker build --file Dockerfile --tag ghcr.io/jamesread/wordle-solver:${{ env.VERSION }} .

    - name: Docker push
      run: docker push ghcr.io/jamesread/wordle-solver:${{ env.VERSION}}
