name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3.1.0
      with:
        username: jamesread
        password: ${{ secrets.CONTAINER_TOKEN }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/jamesread/wordle-solver:$VERSION

    - name: Docker push
      run: docker push ghcr.io/jamesread/wordle-solver:$VERSION
      
